FROM node:12
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied where available (npm@5+)
COPY package*.json ./

ENV http_proxy http://127.0.0.1:3128
ENV https_proxy http://127.0.0.1:3128
ENV HTTP_PROXY http://127.0.0.1:3128
ENV HTTPS_PROXY http://127.0.0.1:3128

# RUN npm config set https-proxy http://localhost:3128/
# RUN npm config set proxy http://localhost:3128/

RUN npm install
# Bundle app source
COPY . .
EXPOSE 8080
CMD [ "npm", "run", "prod" ]