version: "3"
networks:
  udagram:
    driver: bridge
services:
  reverseproxy:
    image: reverseproxy
    build:
      context: udagram-reverseproxy
    ports:
      - 8080:8080
    restart: always
    networks:
      - udagram
  backend-user:
    image: udagram-api-user
    build:
      context: udagram-api-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB                    
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    networks:
      - udagram
  backend-feed:
    image: udagram-api-feed
    build:
      context: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    networks:
      - udagram
  frontend:
    image: udagram-frontend:local
    build:
      context: udagram-frontend
    ports:
      - "8100:80"
    networks:
      - udagram